### ISSUE TITLE
'Agent' object has no attribute 'handle_channel'

### ISSUE THREAD

**Issue by azizullah2017** [scalableminds/chatroom#57] opened 2018-10-24 10:28 UTC
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/Documents/Bot (copy)/rasa_utils/bot.py", line 61, in <module>
    agent.handle_channel(channel, message_preprocessor=preprocessor)
AttributeError: 'Agent' object has no attribute 'handle_channel'

**Comment by hotzenklotz** [comment] 2018-10-25 08:19
This is a duplicate of your previous issues #45. Please do not open duplicate issues. 

Please check the solutions there:
1. Rasa changed the interface for channel handling. See the update Readme: https://github.com/scalableminds/chatroom#advanced-usage-with-a-custom-rasa-core-project-as-custom-channel-from-python
2. Check the answer https://github.com/scalableminds/chatroom/issues/47#issuecomment-428184160
3: Check out the updated example code: https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot.py#L148

**Closed by hotzenklotz** 2018-10-25 08:19 UTC
